### ISSUE TITLE
100 % preview broken

### ISSUE THREAD

**Issue by jerekupari** [rawstudio/rawstudio#12]
(I think I reported this in the rawstudio bugzilla, but it's been offline now for quite a while...)

The 100 % preview (hotkey '*', or "Fit to view") shows mostly just garbage: It only works in the upper left corner of the image. If you try to scroll away from the corner, the image does not move, but blinds of garbage crop the image starting from the upper left corner.

My current desktop machine actually does not show garbage, but plain white. Other builds and machines have usually shown garbage that might have something resembling the real image data.

The regression happened somewhere between commits 30e4efb and 52b9591 (2015-02-19 and 2015-03-03). I have not seen a gtk+3 build of rawstudio where this would work. But the Loupe view (Ctrl + left drag) works.

**Comment by jerekupari** [comment]
This is present in commit 1416a5d (2015-02-24) which is right before 
23f44d1 "Rewrote the preview drawing to be somewhat more GTK-like (and simpler)."

I tried to compile 9292828 (2015-02-24) before the massive "Ported to GTK+-3 - almost works as expected." But it didn't compile:
```
rs-dir-selector.o: In function `row_expanded':
/usr/local/src/rawstudio/src/rs-dir-selector.c:195: undefined reference to `gdk_window_get_type'
```
Also 9c57c87 failed to autogen on Ubuntu 15.10 saying
```
checking for OSMGPSMAP... no
configure: error: Package requirements (osmgpsmap) were not met:

No package 'osmgpsmap' found
```
I have libosmgpsmap-1.0-0-dev installed.

**Comment by jerekupari** [comment]
2015-02-23 git9c57c87 with cherry-picked 68b5e43 (geo support removed) compiles
The bug is present.

**Comment by jerekupari** [comment]
In 2015-02-22 77407a5 the preview works.
And 2015-02-23 4ee938a introduces this bug.
So the problem is in src/rs-preview-widget.c ?
Some calculation going wrong?

**Comment by sergiomb2** [comment]
> I have libosmgpsmap-1.0-0-dev installed.
that is the problem rawstudio only worked with  libosmgpsmap-0.7

**Comment by abrander** [comment]
Thanks for reporting and dissecting this issue. It was simply amazing to dive right into a specific commit introducing the bug. Awesome!

Fixed in 2c74540.
